name: Test and Build

on: [workflow_dispatch]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:      
      - name: clone du proj ds le runner
        uses: actions/checkout@v6
      - name: Check Files
        run: ls -a -l
      - name: install env Node.js
        uses: actions/setup-node@v6
      - name: install dépendances
        run: npm ci
      - name: lancement des tests unitaires
        run: npm run test
      
      
      - name: Mailage en cas de foirage du testage
        if: failure()
        uses: JaSiLez/smtp-notifier@main
        with:
          server_address: ${{ vars.SMTP_SERVER }}
          server_port: ${{ vars.SMTP_PORT }}
          secure: true
          from: ${{ secrets.FROM_EMAIL }}
          to: digitalcity@yopmail.com
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Deployment fail !"
          html_body: "oopsie"


      - name: build du code ts vers le js
        run: npm run build
      - name: chech resultat du build
        run: npm run start

    