name: Test and Build

on: [workflow_dispatch]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:      
      - name: clone du proj ds le runner
        uses: actions/checkout@v6
      - name: Check Files
        run: ls -a -l
      - name: install env Node.js
        uses: actions/setup-node@v6
      - name: install dépendances
        run: npm ci
      - name: lancement des tests unitaires
        run: npm run test
      - name: mailer test
        uses: dawidd6/action-send-mail@<REF>

      - name: Send Email si test fail
        if: failure()
        uses: ksatriow/action-mailer@v1
        with:
          smtp-server: ${{vars.SMTP_SERVER}}
          smtp-port: ${{vars.SMTP_PORT}}
          from-email: ${{ secrets.FROM_EMAIL }}
          to-email: "digitalcity@yopmail.com"
          username: ${{secrets.SMTP_USERNAME}}
          password: ${{secrets.SMTP_PASSWORD}}
          subject: "🚀 Deployment fail"
          body: "oopsie"


      - name: build du code ts vers le js
        run: npm run build
      - name: chech resultat du build
        run: npm run start

    