name: Test and Build

on: [workflow_dispatch]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:      
      - name: clone du proj ds le runner
        uses: actions/checkout@v6
      - name: Check Files
        run: ls -a -l
      - name: install env Node.js
        uses: actions/setup-node@v6
      - name: install dépendances
        run: npm ci
      - name: lancement des tests unitaires
        run: npm run test

    